/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    Chip: typeof import('primevue/chip')['default']
    ClickableHistory: typeof import('./src/components/ClickableHistory.vue')['default']
    DefinitionDisplay: typeof import('./src/components/DefinitionDisplay.vue')['default']
    DictionaryResultsCard: typeof import('./src/components/DictionaryResultsCard.vue')['default']
    Divider: typeof import('primevue/divider')['default']
    Frequency: typeof import('./src/components/Frequency.vue')['default']
    FrequencyMeter: typeof import('./src/components/FrequencyMeter.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    History: typeof import('./src/components/History.vue')['default']
    HistoryComponent: typeof import('./src/components/HistoryComponent.vue')['default']
    HistoryList: typeof import('./src/components/HistoryList.vue')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Message: typeof import('primevue/message')['default']
    NoResults: typeof import('./src/components/NoResults.vue')['default']
    PartOfSpeechFilterBar: typeof import('./src/components/PartOfSpeechFilterBar.vue')['default']
    ProgressSpinner: typeof import('primevue/progressspinner')['default']
    SearchBar: typeof import('./src/components/SearchBar.vue')['default']
    SearchComponent: typeof import('./src/components/SearchComponent.vue')['default']
    SelectButton: typeof import('primevue/selectbutton')['default']
    TailwindPrimeVueTest: typeof import('./src/components/TailwindPrimeVueTest.vue')['default']
    ThemeToggle: typeof import('./src/components/ThemeToggle.vue')['default']
    WordChip: typeof import('./src/components/WordChip.vue')['default']
    WordChips: typeof import('./src/components/WordChips.vue')['default']
    WordSearch: typeof import('./src/components/WordSearch.vue')['default']
  }
  export interface GlobalDirectives {
    Tooltip: typeof import('primevue/tooltip')['default']
  }
}
